Add missing `yarn install` to `prepublish` scritpt
I noticed this script was running into an error without this step: 

```
node_modules/@types/node/globals.d.ts(347,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
``` 

Adding `yarn install` after `yarn clean` fixed the issue.